name: SpirographStudio
options:
  bundleIdPrefix: com.spirographstudio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"       # iPhone only
    SUPPORTS_MACCATALYST: "NO"
    ENABLE_BITCODE: "NO"
    SWIFT_STRICT_CONCURRENCY: "minimal"

targets:
  SpirographStudio:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    info:
      path: SpirographStudio/Resources/Info.plist
      properties:
        CFBundleDisplayName: "Spirograph Studio"
        NSPhotoLibraryAddUsageDescription: "Spirograph Studio saves your artwork to your Photos library."
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
    sources:
      - path: SpirographStudio
        excludes:
          - Tests/**
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spirographstudio.app
        INFOPLIST_FILE: SpirographStudio/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_EMIT_LOC_STRINGS: "YES"
    dependencies:
      - sdk: Photos.framework

  SpirographStudioTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SpirographStudio/Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spirographstudio.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SpirographStudio.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/SpirographStudio"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: SpirographStudio

schemes:
  SpirographStudio:
    build:
      targets:
        SpirographStudio: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SpirographStudioTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
